require("depdiller.plugins-setup") -- at the top of the file
require("depdiller.core.options")
require("depdiller.core.colorscheme")
require("depdiller.core.keymaps")
require("depdiller.plugins.comment")
require("depdiller.plugins.nvim-tree")
require("depdiller.plugins.lualine")
require("depdiller.plugins.nvim-cmp")
require("depdiller.plugins.lsp.mason")
require("depdiller.plugins.lsp.lspsaga")
require("depdiller.plugins.lsp.lspconfig")
require("depdiller.plugins.lsp.null-ls")
require("depdiller.plugins.autopairs")
require("depdiller.plugins.treesitter")
require("depdiller.plugins.gitsigns")
require("depdiller.plugins.harpoon")
require("depdiller.plugins.telescope")
require("depdiller.plugins.neoscroll")
